### ISSUE TITLE
Contributing to Web Sites page

### ISSUE THREAD

**Issue by ajpiano** [jquery/contribute.jquery.org#11]
In `page/web.md`, following the mold of the triage page, put together instructions on the basics of contributing to jQuery Foundation websites, including: 

- [x] high level overview of jquery-wp-content and content repos, why we made it work that way instead of wikis and a million different wordpress installs
- [x] outlining dependencies
- [x] basics of editing workflow and deploy process
- [x] links to all the website repos
- [ ] when you'll need to edit web-base-template vs a content repo
- [ ] current status of where people should be contributing
- [x] list of exceptions (sites not on jquery-wp-content, whether they ever will be)

**Comment by arthurvr** [comment]
> current status of where people should be contributing

Well guys, what is the current status of where people should be contributing? IMHO this shouldn't be on the site - it isn't and in fact contributions are welcome/needed everywhere.

**Comment by scottgonzalez** [comment]
I think this can be closed. If there are specific items to be addressed, they should be in their own issues at this point.
