### ISSUE TITLE
CLA Checker: Show time of attempted verification

### ISSUE THREAD

**Issue by gibson042** [jquery/contribute.jquery.org#110]
For technical reasons, we don't automatically recheck pull requests when a contributor signs the CLA. But pages/CLA/status.md doesn't provide enough information on its own to detect post-failure resolution, because it lacks the invocation time.

We should add text to the effect of "The following authors didn't have appropriate CLA signatures _as of [datetime]_", and also instructions to reactivate the checker by pushing a new commit to each affected pull request (perhaps suggesting `git commit --allow-empty -m '[CLA]: Recheck'`).

**Comment by cvrebert** [comment]
Have you considered having the bot listen for PR comments and having some magic comment force a CLA re-check?

**Comment by arschmitz** [comment]
@gibson042 @cvrebert The only reason we don't currently re-check is just that it has not been implemented, the cla checker is very new. There are 2 open issues for this https://github.com/jquery/jquery-license/issues/2 to implement the ability to recheck a PR, and https://github.com/jquery/jquery-license/issues/6 Which is to implement auto re-checks ( and also includes discussion of re-checking based on comments ) 

`--allow-empty` would work just not sure we want to recommend that? @scottgonzalez thoughts?

**Comment by scottgonzalez** [comment]
Moved to https://github.com/jquery/jquery-license/issues/30 since that's where we've been tracking all of the CLA checker changes.

I'd rather see someone just implement https://github.com/jquery/jquery-license/issues/6 instead of suggesting empty commits.
