### ISSUE TITLE
Wrong link to the github repository for the http://sizzlejs.com/  website

### ISSUE THREAD

**Issue by najela** [jquery/contribute.jquery.org#113]
[This page](https://github.com/jquery/contribute.jquery.org/edit/master/pages/web-sites.md#L261) provides the link to the github repository for the [sizzleJS website](http://sizzlejs.com/). The link appears to be broken however. I tried searching for the repository for that website but I couldn't find one. Does it even exist?

**Comment by dmethvin** [comment]
Not sure where the sizzlejs.com web site is located, but there doesn't seem to be a repo for it in /jquery. @timmywil?

**Comment by scottgonzalez** [comment]
It should be pretty obvious that sizzlejs.com has never been part of jquery-wp-content. It's a one-off that never got any attention.

**Comment by najela** [comment]
@scottgonzalez  Does that mean we should delete [line 261](https://github.com/jquery/contribute.jquery.org/edit/master/pages/web-sites.md#L261)?

**Comment by scottgonzalez** [comment]
Yeah. Note that it's already in the [list of sites that don't use jquery-wp-content](http://contribute.jquery.org/web-sites/#not-live-content-migration-in-progress-planned).

**Comment by najela** [comment]
Okay... I'll submit a PR then

**Comment by najela** [comment]
@scottgonzalez  @dmethvin https://github.com/jquery/contribute.jquery.org/pull/114 resolves this issue

**Comment by arthurvr** [comment]
We should probably first discuss the long-term plans with that site before just deciding to remove it everywhere.

I'm fine with removing it from that list but we can't just let the site of one of our projects die. First of all, what was the reason the repo was removed and where does it live now?

**Comment by scottgonzalez** [comment]
There was never a repository for the existing site. There *was* a repository for the new site, which contained a single page of content that was copy/pasted from the live site, but was never worked on and never deployed. You can see what state it was in on http://stage.sizzlejs.com/. Since nobody ever expressed any desire to work on it, and having the repo exist but not be the actual site was confusing, that repo was deleted a long time ago.

**Comment by arthurvr** [comment]
Okay, thanks for the info. I'm +1 for removing it.
