### ISSUE TITLE
Deploying command is kind of confusing

### ISSUE THREAD

**Issue by agcolom** [jquery/contribute.jquery.org#116]
At the bottom of [this section](http://contribute.jquery.org/web-sites/#deploying-to-staging-and-production-environments) we say to use ```git push --tags origin master```. However, everywhere else on the contribute site, [we say](http://contribute.jquery.org/commits-and-pull-requests/) to fork the repo, clone the fork which will be origin and add the main jquery repo as upstream. I'm proposing to replace ```git push --tags origin master``` to ```git push --tags upstream master```. Any comments or objections?

**Comment by jzaefferer** [comment]
It looks to me like the parts using "upstream" are written for contributors, the one using "origin" for maintainers. We should keep those separate, so moving that "deploying" section elsewhere would be better than renaming the remote.

**Comment by agcolom** [comment]
@jzaefferer I agree with that. I'd be happy to maybe have a warning note then, reminding people that they should check whether they should push to origin or upstream (many maintainers started as contributors and would have the remotes inline with the contributor's recommendations. What do you think?

**Comment by jzaefferer** [comment]
That makes sense.

**Comment by mzgol** [comment]
This seems confusing to me. Why not settle on `origin` for everything? I always use `origin` for the upstream repo (this is the default) and then add my fork if needed under my GitHub name as a remote name (i.e. `mzgol`). Changing `upstream` to `origin` just because someone became a maintainer seems weird.

**Comment by agcolom** [comment]
@mzgol My understanding is that contributors have been recommended to use upstream for the upstream/main repo and origin for their fork, and that is everywhere in the contribute site. I don't think we're going to change that. However, when used to follow the instructions on the contribute site, it can be confusing to suddenly be told to use ```origin``` and not ```upstream```. While this section is for maintainers and it would be fair to expect maintainers to be aware of their setup and correct ```origin``` to ```upstream``` in that command, I think a reminder to check their remote before tagging and pushing can't do any harm and may help prevent mistakes.

**Comment by mzgol** [comment]
Choice of specific names is personal taste so if we have `upstream`+`origin` everywhere then let's keep it. I just don't understand why we can't advise identical setup for maintainers as for contributors. After all, maintainers also submit PRs and also do it often from their own forks. I don't see the gains of separating those two cases.

For me it'd be easiest to understand if the only difference between Git setup of contributors & maintainers would be that the latter ones can push to `upstream`.

**Comment by scottgonzalez** [comment]
> For me it'd be easiest to understand if the only difference between Git setup of contributors & maintainers would be that the latter ones can push to `upstream`.

That's exactly what @agcolom originally suggested.

**Comment by mzgol** [comment]
Right, sorry for the confusion. +1 to @agcolom then.

**Comment by arthurvr** [comment]
:+1: to changing together with adding a note to make sure people double check.

**Comment by agcolom** [comment]
@jzaefferer @mzgol @scottgonzalez Please check the PR and let me know if the wording looks good to you. Here's a screenshot also:
![clarifydeploy](https://cloud.githubusercontent.com/assets/688413/7444506/0e94af52-f17e-11e4-9f45-a1f47fe1d40a.png)
