### ISSUE TITLE
Commits and Pull Requests: Inconsistent with current workflow

### ISSUE THREAD

**Issue by AurelioDeRosa** [jquery/contribute.jquery.org#125]
The section [Commit Guidelines](http://contribute.jquery.org/commits-and-pull-requests/#commit-guidelines) of the [Commits and Pull Requests page](http://contribute.jquery.org/commits-and-pull-requests), is inconsistent with the current workflow. In particular, it suggests that after the "Fixes" word there should be the sharp or pound sign (`#`) followed by the ID of the issue fixed (e.g.: **Fixes #​100**). However, we specify that line with gh-ID (e.g. **Fixes gh-​100**).

What's the suggest way? Should we update the section?

**Comment by arschmitz** [comment]
@AurelioDeRosa We use both. We have projects that don't use github for issues. The gh is to differentiate. For example when referencing trac issues on jQuery UI it should be a # but when referencing a pull request it should be gh-. As we add projects having this information here might become a bit unmaintainable as projects potentially choose different styles. 

This is really a general problem with the current contribute website though.

**Comment by arthurvr** [comment]
> As we add projects having this information here might become a bit unmaintainable as projects potentially choose different styles.

Although it would be nice if it's somewhat consistent, I agree. There's only one project that still uses Trac anyways.

The fact that Core switched from Trac to GitHub doesn't make this discussion more easy. #1234 could mean both Trac 1234 and GitHub issue 1234.

Ref https://github.com/jquery/jquery/issues/2019

**Comment by AurelioDeRosa** [comment]
@arschmitz if you think it's not worth updating the page, feel free to close this issue.

**Comment by AurelioDeRosa** [comment]
This is a very old issue. Is there any new opinion on this or action required? Or can we close it?

**Comment by dmethvin** [comment]
I think this is best resolved at the project level, so that we don't need to enumerate all the practices that different projects follow. For most projects the current text is fine I would think, so this ticket could be closed.

**Comment by AurelioDeRosa** [comment]
Thank you @dmethvin.
