### ISSUE TITLE
Document focus problems in IE

### ISSUE THREAD

**Issue by mgol** [jquery/contribute.jquery.org#126]
All versions of IE (including IE 11) fire focus & blur events asynchronously; we often get bug reports about that: [jquery/jquery#trac-13026](http://bugs.jquery.com/ticket/13026), jquery/jquery#1758, jquery/jquery#2511 to name just a few.

Thankfully, it was fixed in Microsoft Edge but IE 11 will stay forever as it is.

We should document this as one of the things on the "Won't fix" list at https://contribute.jquery.org/wont-fix/

**Comment by wmill** [comment]
+1

**Comment by dmethvin** [comment]
https://github.com/jquery/jquery/wiki/Won't-Fix#focus-and-blur-event-order
