### ISSUE TITLE
drag actions not working on microsoft touch screen laptops

### ISSUE THREAD

**Issue by pandu5164** [jquery/contribute.jquery.org#142]
Hi,
I am using drag actions in my page. But my laptop is not able to drag elements by touch.It only works with mouse.
I use jquery 1.11.3 version.
Device I use:- Lenovo Yoga 510 (Running windows 10 OS-x64 bit)
Please let me know if there is any fix available.

**Comment by dmethvin** [comment]
Please ask for help on StackOverflow or some other help forum. Thanks!
