### ISSUE TITLE
Document how to be a maintainer

### ISSUE THREAD

**Issue by jzaefferer** [jquery/contribute.jquery.org#27]
We provide information for contributors, but nothing for maintainers. While we don't add people to jQuery Core, we should generally give out more write access to spread the load. I've never seen anyone abuse that "power", while they usually become more engaged in the project, since they now have more authority and try to make that up in the necessary responsibility.

I've started putting together some guidelines for reviewing PRs, should be valid at least for QUnit and mostly jQuery UI: https://gist.github.com/jzaefferer/a93958b48faa55ff84c5

Do we just give maintainers read access to the CLA document? Or is there some other option?

**Comment by agcolom** [comment]
@RedWolves @scottgonzalez @arthurvr How about adding a new heading in the left nav with the title "For maintainers..." just trying to keep it consistent with the existing tone on this menu...  
![proposedmenu](https://cloud.githubusercontent.com/assets/688413/7248401/5114d546-e80a-11e4-82f6-1f9e243c1810.png)

**Comment by jzaefferer** [comment]
That looks good to me.

Regarding https://github.com/jquery/contribute.jquery.org/blob/master/pages/repo-maintainers-guide.md - we can heavily simplify the CLA section, now that its mostly automated.

**Comment by scottgonzalez** [comment]
Seems fine to me.
