### ISSUE TITLE
Documentation on setting Git config

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/contribute.jquery.org#51]
We need to document how to set your name and email address in Git. We should link to this from Contributing to Code, Commits and Pull Requests, and even the CLA page.

**Comment by arthurvr** [comment]
Isn't this duplicate of https://github.com/jquery/contribute.jquery.org/issues/40?

**Comment by scottgonzalez** [comment]
Yup, I guess this has come up enough that I've filed it twice :-P
