### ISSUE TITLE
Documentation page

### ISSUE THREAD

**Issue by ajpiano** [jquery/contribute.jquery.org#8]
In `page/documentation.md`, following the mold of the triage page, put together instructions on the basics of contributing documentation to any jQuery project, e.g., forking repos, making pull requests, following the style guide, using grunt, etc, with links to all the project repos

**Comment by arthurvr** [comment]
> Maybe close this one and open another regarding style guides?

@kswedberg We already have https://github.com/jquery/contribute.jquery.org/issues/75, is that what you meant?

**Comment by kswedberg** [comment]
@arthurvr :+1:
