### ISSUE TITLE
Rework HTML Style Guide

### ISSUE THREAD

**Issue by sfrisk** [jquery/contribute.jquery.org#92]
The current html style guide is very limited (http://contribute.jquery.org/style-guide/html/).  Rework html style guide to be more robust to handle future development for html heavy projects.

**Comment by MichaelArestad** [comment]
**Accessibility**
> maybe something on accessible markup, especially when it comes to forms/images/etc?

I would definitely include references to proper accessible markup and how to properly write an `alt` attribute.

I would potentially add a bit about adding  `<title>` and `<desc>` elements to inline SVGs.[#](http://www.sitepoint.com/tips-accessible-svg/)

**Forms**
I would include:
* proper locations for label element in conjunction with various input types.
* proper use of placeholder text

**Comment by Slayslot** [comment]
http://validator.w3.org/ can be used for html validation ?

**Comment by arschmitz** [comment]
@Slayslot this is about style not validity

**Comment by Slayslot** [comment]
@arschmitz Yes, but @sfrisk had it in her suggested items list, so if we're going to explicitly ask the users to write valid html why not recommend them to check it from here as well? Google does the same thing in their HTML style guide. https://google-styleguide.googlecode.com/svn/trunk/htmlcssguide.xml#HTML_Validity

**Comment by scottgonzalez** [comment]
Just a note about validators: While validator.w3.org is certainly useful, we do use validator.nu for our automated testing via [grunt-html](https://www.npmjs.com/package/grunt-html).

**Comment by sfrisk** [comment]
It might be useful to list our preference for validator.nu in the html style guide, but in general the HTML style guide should focus more on style since we're looking to expand the HTML style guide to be similar to the CSS/JS ones.

**Comment by Slayslot** [comment]
So we can just mention that we use validator.nu for automated testing via [grunt-html](https://www.npmjs.com/package/grunt-html) and further recommend them to use it before posting html.

**Comment by scottgonzalez** [comment]
Before posting what HTML? If it's a project that's using grunt-html, it will automatically be checked. Having to manually check validation is extremely tedious and time consuming.

**Comment by Slayslot** [comment]
I've been reading [Code Guide](http://codeguide.co) and [Google's HTML style guide](https://google-styleguide.googlecode.com/svn/trunk/htmlcssguide.xml) and have come up with the following things that should be included in the style guide:
* Remove Trailing Whitespace.
* Separation of Concerns (No inline styles or scripts).
* HTML semantics(Using proper HTML elements wherever needed).
* Attributes to be placed in order(This will increase readability.Order is mentioned after the list).
* Reducing Markup(Avoid superfluous parent elements).
* Avoid JS Generated Markup.
* Not separating attributes with two or more white spaces.
* Line break after br element.
* Wrapping form control with label element.
* Using appropriate type element for input element.
* Add value attribute to input type="submit".
* Not using placeholder for labelling. 
 
The Attribute order being:
1. class
2. id,name
3. data-*
4. src,for,type,href,value
5. title,alt,
6. aria-*,role

**Comment by scottgonzalez** [comment]
> Wrapping form control with label element.

We need evidence this is a good idea. This has historically been bad for accessibility.

> Using appropriate type element for input element.

You mean `type` *attribute*. This isn't necessary for text fields, but it depends if you want to easily target text inputs via CSS.

> Add value attribute to input type="submit".

Only needed if you're using multiple submit elements on the same form.

> The Attribute order being:

Is there an explanation of why this order is chosen?

**Comment by Slayslot** [comment]
>Before posting what HTML? If it's a project that's using grunt-html, it will automatically be checked. Having to manually check validation is extremely tedious and time consuming.

Point taken.

>We need evidence this is a good idea. This has historically been bad for accessibility.

I, quite frankly didn't know that. On a bit research I found [this](http://ux.stackexchange.com/questions/35289/input-checkboxes-wrapped-inside-labels/35297#35297) . So at least radio buttons and checkboxes take advantage from this method.

>You mean type attribute. This isn't necessary for text fields, but it depends if you want to easily target text inputs via CSS.

Would it hurt if a type attribute is included for text field? I'm honestly asking here? Because if it won't hurt then it only makes it easier for everyone to write and understand. Similarly I couldn't understand the Indentation section from the existing HTML style guide. `Don't indent inside html, body, script, or style. Indent inside head and all other elements` Why not indent inside html,body,script and style? I get that if you're using tabs it might push the content further right and in turn decrease readability. But, if we use 2 spaces to indent instead of tab, wouldn't that make reading and writing more consistent? You indent inside every element and indent with only 2 spaces. Sweet and simple. 
>Is there an explanation of why this order is chosen?

Well, let me just quote [Codeguide](http://codeguide.co/) `Classes make for great reusable components, so they come first. Ids are more specific and should be used sparingly (e.g., for in-page bookmarks), so they come second.` No further explanation is given. I feel that any logical order can be decided upon just to create a standard people can familiarize themselves around which will in turn lead towards better readability.

**Comment by scottgonzalez** [comment]
> I, quite frankly didn't know that. On a bit research I found this . So at least radio buttons and checkboxes take advantage from this method.

That answer says nothing about accessibility, but note that the comments on the answer say to use the `for` attribute rather than relying on implicit association via wrapping.

> Would it hurt if a type attribute is included for text field?

It doesn't hurt, it's just not necessary. It's the same as explicitly passing the same values as default options in your JavaScript.

> Why not indent inside html,body,script and style?

Because it doesn't actually improve readability and instead just pushes everything further out.

> But, if we use 2 spaces to indent instead of tab, wouldn't that make reading and writing more consistent?

I'll go on record as saying that I would absolutely hate for any of our style guides to require 2 spaces. I honestly don't understand how the world hasn't settled on tabs by now.

**Comment by dmethvin** [comment]
> > Would it hurt if a type attribute is included for text field?

> It doesn't hurt, it's just not necessary. 

As you noted though, it's necessary if you want to style text inputs since `<input />` won't match a CSS rule of `input[type=text]`.

**Comment by Slayslot** [comment]
>That answer says nothing about accessibility, but note that the comments on the answer say to use the for attribute rather than relying on implicit association via wrapping.

I was focusing more on the increased hit zone but I do get your point. What, in your opinion, would be the best way for this?

>It doesn't hurt, it's just not necessary. It's the same as explicitly passing the same values as default options in your JavaScript.

okay, but this extra effort will make it easier to style them in CSS. 

>I'll go on record as saying that I would absolutely hate for any of our style guides to require 2 spaces. I honestly don't understand how the world hasn't settled on tabs by now.

Frankly speaking, I too use tabs. And, now that you've pointed out your hate for 2 spaces I realize that I hated it too. For the fact that the deeper the element, that you're working on, is nested the tedious it gets to add spaces. Adding 2*n spaces after every line will obviously be tedious than adding n tabs. I would really like to see others view on this and the second list I've added in my comments edit. As both of these have their pros and cons.

**Comment by scottgonzalez** [comment]
> I was focusing more on the increased hit zone but I do get your point. What, in your opinion, would be the best way for this?

Keep them separate and use the `for` attribute.

> okay, but this extra effort will make it easier to style them in CSS.

I would prefer if we didn't *require* `type` attributes, but I'm not strongly against it if we have a tool that's checking for it.

**Comment by Slayslot** [comment]
>Keep them separate and use the for attribute.

Alright, we can keep that.

>I would prefer if we didn't require type attributes, but I'm not strongly against it if we have a tool that's checking for it.

HTML validation wouldn't check for that?

**Comment by scottgonzalez** [comment]
> HTML validation wouldn't check for that?

I'm not aware of any validator that checks for an optional attribute to be required.

**Comment by Slayslot** [comment]
>I'm not aware of any validator that checks for an optional attribute to be required.

Hmm, didn't think so. This will be problematic then.

**Comment by Slayslot** [comment]
Just to move things further and for everyone's ease I've made these lists consisting everything that has been discussed here so far.

**Changes that nobody has any objection against:**
* Remove Trailing Whitespace.
* Separation of Concerns (No inline styles or scripts).
* HTML semantics(Using proper HTML elements wherever needed).
* Attributes to be placed in order(Order to be decided).
* Reducing Markup(Avoid superfluous parent elements).
* Avoid JS Generated Markup.
* Not separating attributes with two or more white spaces.
* Line break after `br` element.
* Using `for` in `label`.
* Not using `placeholder` for labelling.
* alt text for images.
* double quotation over single quotation-done
* No use of `on*` attributes.

**Changes that have had no discussion:**
* Should we omit protocol or not?
* Adding `title` attribute to alternate stylesheets?
* Using TODO in comments.

**Changes with conflict:**
* Using appropriate `type` element for `input` element: Need a tool to implement.
* Two space indentation or tabs? : Both have their advantages and disadvantages.

**Comment by scottgonzalez** [comment]
> Attributes to be placed in order(Order to be decided).

I'm not really convinced an order is necessary. There are a few attributes (`rel`, `type`, `src`, `href`) that I think should always be in the front, but I don't really see much value in defining extensive orders.

> Avoid JS Generated Markup.

I'm not really sure how this is tied to an HTML style guide.

> Line break after br element.

I'm not sure what the intention is. `<br>` elements are pretty rare in good markup, I'm not sure this requires an explicit rules.

> No use of on* attributes.

How is this different from separation of concerns?

> Should we omit protocol or not?

That's a highly dependent question, isn't it?

> Adding title attribute to alternate stylesheets?

Why?

> Using TODO in comments.

If it's a TODO, yes. I don't see why this would be included in a style guide.

> Two space indentation or tabs? : Both have their advantages and disadvantages.

I would expect that jQuery projects won't follow the style guide if the rule isn't tabs.

**Comment by scottgonzalez** [comment]
> Two space indentation or tabs? : Both have their advantages and disadvantages.

>> I would expect that jQuery projects won't follow the style guide if the rule isn't tabs.

Phrased another way: Every project that this is intended to apply to already has a rule to use tabs.

**Comment by Slayslot** [comment]
>I'm not really convinced an order is necessary. There are a few attributes (rel, type, src, href) that I think should always be in the front, but I don't really see much value in defining extensive orders.

Alright, if not an extensive order at least we can tell people to keep the few attributes that you stated(and maybe add `class` to that?) in the front.

>I'm not really sure how this is tied to an HTML style guide.

include it in the JS guide then?

>I'm not sure what the intention is. <br> elements are pretty rare in good markup, I'm not sure this requires an explicit rules.

Makes sense.

>How is this different from separation of concerns?

That's my bad.

>That's a highly dependent question, isn't it?

Dependent on whether the asset is available for both protocols?

>Why?

To make it clear as to what the alternate stylesheet is there for. I am not sure if this is entirely necessary or if it will help in any way, hence, it was placed in the dilemma list.

>If it's a TODO, yes. I don't see why this would be included in a style guide.

To define a proper way to write TODOs. Taking the example from Google's style guide `TODO(john.doe): revisit centering`.

>Phrased another way: Every project that this is intended to apply to already has a rule to use tabs.

Fair enough, tabs it is. But we'll have to make the wordings in the existing style guide clearer and with a better example.

**Comment by scottgonzalez** [comment]
> Avoid JS Generated Markup.

>> I'm not really sure how this is tied to an HTML style guide.

>>> include it in the JS guide then?

I'm not sure it belongs there either. This is a project by project decision. It's highly dependent on what you're trying to accomplish.

> Using TODO in comments.

>> If it's a TODO, yes. I don't see why this would be included in a style guide.

>>> To define a proper way to write TODOs. Taking the example from Google's style guide `TODO(john.doe): revisit centering`.

We don't have a single project that currently writes TODOs in that format. I think this is overkill. Most TODOs belong in issues anyway.

**Comment by Slayslot** [comment]
>I'm not sure it belongs there either. This is a project by project decision. It's highly dependent on what you're trying to accomplish.

Sure, but markup written in JS makes the markup just hard to find and edit if need be. So, if it can be  avoided, then why not?

>We don't have a single project that currently writes TODOs in that format. I think this is overkill. Most TODOs belong in issues anyway.

Just thought it was a decent idea. You are correct though, Most TODOs do belong in issues.

**Comment by arschmitz** [comment]
> Sure, but markup written in JS makes the markup just hard to find and edit if need be. So, if it can be avoided, then why not?

Because if this is to be used by projects like jQuery Mobile and UI, this makes no since they are projects that create JS based widgets and so intentionally generate markup. This is something that needs to be  evaluated on a case by case basis, and so makes no sense in a style guide.

**Comment by Slayslot** [comment]
>@slayslot Because if this is to be used by projects like jQuery Mobile and UI, this makes no sense, they are projects that create JS based widgets and so intentionally generate markup. This is something that needs to be evaluated on a case by case basis, and so makes no sense in a style guide.

That does make sense. Don't I feel stupid now. I'll update the list.

**Comment by Slayslot** [comment]
Before updating the list, I wanted to confirm the status of these two:
>Should we omit protocol or not?
>Adding title attribute to alternate stylesheets?
