### ISSUE TITLE
Add notice about !important to css style guide

### ISSUE THREAD

**Issue by arschmitz** [jquery/contribute.jquery.org#96]
I think we should either completely forbid `!important` and update the csslint settings or we should at least add a note STRONGLY discouraging it.

/cc @jquery/chassis @MichaelArestad @kristoferjoseph

**Comment by sfrisk** [comment]
:+1: 

I can add it to the CSS Style Guide if you guys want.

**Comment by MichaelArestad** [comment]
There are definitely occasions when it's needed, but by default, I would make !important forbidden. :
